# Header
menu:
  主页: /
  归档: /archives
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: true
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: ture

# For CN Users
# 配置网易云跟帖 这里填写 productKey 
product_key: 
# 配置搜狐畅言 分别填写 appid 和 conf
cy_appid: 
cy_conf: 

# Miscellaneous
google_analytics: 
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
